<script>
 import {safeHttpUrl} from '../../../safe-url.mjs'
 import {untrack} from 'svelte'
 import {API} from './api.js'
 import {RELATIONSHIPS,ROBOTS} from '../../../domain-library.mjs'
 let {domain,platform,saved=null,onSaved=()=>{}}=$props()
 let relationships=$state(untrack(()=>saved?.relationships??[])),robots=$state(untrack(()=>saved?.robots??'Not checked')),notes=$state(untrack(()=>saved?.notes??'')),busy=$state(false),error=$state(''),message=$state('')
 async function save(){busy=true;error='';message='';try{const r=await fetch(`${API}/api/domain-library/platform`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,platform:platform.id,relationships,robots,notes})});const value=await r.json();if(!r.ok)throw Error(value.error);onSaved(value);message='Saved'}catch(e){error=e.message}finally{busy=false}}
</script>
<tr><th scope="row">{platform.label}</th><td><fieldset disabled={busy}><legend>Relationship</legend>{#each RELATIONSHIPS as type}<label><input type="checkbox" bind:group={relationships} value={type}/>{type}</label>{/each}</fieldset></td><td><label>Robots.txt status<select bind:value={robots} disabled={busy}>{#each ROBOTS as value}<option>{value}</option>{/each}</select></label></td><td>{#if saved?.tracker_evidence?.length}<section class="tracker"><strong>Tow tracker</strong><small>Recorded events; dates and lawsuit status are from the tracker. A deal does not necessarily mean an active partnership.</small><ul>{#each saved.tracker_evidence as event}<li><b>{event.types.join(' + ')}</b> · {event.date || 'Date not listed'}{#if event.status} · {event.status}{/if}<small>{event.organizations.slice(0,2).join(', ')}{event.organizations.length>2 ? ` + ${event.organizations.length-2} others` : ''}</small><a href={safeHttpUrl(event.url)??undefined} target="_blank" rel="noreferrer">Tracker</a>{#each (event.sources || []).filter(url=>/^https?:\/\//.test(url)) as source,i} · <a href={source} target="_blank" rel="noreferrer">Source {i+1}</a>{/each}</li>{/each}</ul></section>{/if}<label>Evidence / notes<textarea bind:value={notes} disabled={busy} maxlength="2000" placeholder="Bot name, date checked, relationship details or evidence link"></textarea></label><button onclick={save} disabled={busy}>{busy?'Saving…':'Save'}</button><span role="status">{message}</span>{#if saved?.updated_at}<small>Last saved {new Date(saved.updated_at).toLocaleDateString()}</small>{/if}{#if error}<p role="alert">{error}</p>{/if}</td></tr>
<style>
 .tracker{font-size:12px;margin-bottom:12px;max-width:480px}.tracker ul{padding-left:16px;margin:8px 0}.tracker li{margin-bottom:10px;line-height:1.5}.tracker a{color:var(--accent);text-decoration:underline}
 th,td{padding:14px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:13px;min-width:115px}fieldset{border:0;padding:0;margin:0;min-width:160px}legend{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}label{display:block;font-size:12px;color:var(--muted);margin-bottom:7px}input{margin-right:6px}select,textarea{display:block;width:100%;box-sizing:border-box;font:inherit;margin-top:7px;padding:8px;border:1px solid var(--line);border-radius:5px;background:var(--card);color:var(--text)}select{min-width:165px}textarea{min-width:200px;min-height:82px;resize:vertical}button{padding:6px 12px;background:var(--card);border:1px solid var(--line);border-radius:5px;cursor:pointer}span,small{display:block;font-size:11px;color:var(--muted);margin-top:6px}p{color:var(--danger);font-size:12px}
</style>
