<script>
 import {onMount} from 'svelte'
 import {domainComparison,domainRankings} from './study.js'
 import {API} from './api.js'
 import DomainPlatformRow from './DomainPlatformRow.svelte'
 import {DOMAIN_CATEGORIES,DOMAIN_PLATFORMS} from '../../../domain-library.mjs'
 let {rows=[]}=$props()
 let tab=$state('compare'),query=$state(''),channel=$state('All'),variant=$state('All'),limit=$state(20)
 const rankings=$derived(domainRankings(rows,{channel,variant}))
 const comparison=$derived(domainComparison(rows))
 const inventory=$derived(comparison.inventory)
 let selected=$state(''),categories=$state([...DOMAIN_CATEGORIES]),domains=$state({}),metadata=$state({}),custom=$state(''),error=$state(''),busy=$state(false),loaded=$state(false),notice=$state('')
 const domain=$derived(inventory.domains.some(d=>d.domain===selected)?selected:inventory.domains[0]?.domain)
 async function request(path,method,body){const r=await fetch(`${API}/api/domain-library${path}`,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed');return value}
 async function load(){try{const value=await request('','GET');categories=value.categories;domains=value.domains;metadata=value.platforms;loaded=true}catch(e){error=e.message}}
 onMount(load)
 async function classify(target,value){busy=true;error='';notice='';try{const saved=await request('/domain','PUT',{domain:target,category:value||null});domains={...domains,[target]:saved};notice='Category saved'}catch(e){error=e.message}finally{busy=false}}
 async function addCategory(){busy=true;error='';notice='';try{const saved=await request('/categories','POST',{name:custom});categories=[...new Set([...categories,saved.name])];custom='';notice=`Added category: ${saved.name}`}catch(e){error=e.message}finally{busy=false}}
 function platformSaved(value){metadata={...metadata,[`${value.domain}:${value.platform}`]:value}}
</script>
<nav aria-label="Citation library views"><button class:active={tab==='compare'} aria-pressed={tab==='compare'} onclick={()=>tab='compare'}>Most cited domains</button><button class:active={tab==='details'} aria-pressed={tab==='details'} onclick={()=>tab='details'}>Platform | Relationship | Robots.txt</button></nav>
{#if error}<p role="alert" class="error">{error}</p>{/if}
{#if !inventory.domains.length}<p>No cited domains for this selection.</p>{:else}
{#if tab==='compare'}
 <div class="toolbar"><label>Find a domain<input type="search" bind:value={query} placeholder="Search domains"/></label><form onsubmit={e=>{e.preventDefault();addCategory()}}><label>Add a category<input bind:value={custom} maxlength="80" placeholder="Category name" required/></label><button disabled={busy||!loaded||!custom.trim()}>Add category</button></form></div>
 <div class="ranking-filters"><label>Responses<select bind:value={channel}><option value="All">Browser + API</option><option>Browser</option><option>API</option></select></label><label>Question version<select bind:value={variant}><option value="All">Original + Recent news</option><option>Original</option><option>Recent news</option></select></label><label>Show per platform<select bind:value={limit}><option value={10}>Top 10</option><option value={20}>Top 20</option><option value={50}>Top 50</option><option value={0}>All domains</option></select></label></div>
 <p class="definition">Ranked separately for each platform. Percentages show how often a domain appears in captured responses; each response counts once per domain. No-search answers are excluded.</p>
 <p role="status">{notice}</p>
 <div class="rankings">{#each rankings as platform}<section class="ranking" aria-label={`Most cited domains — ${platform.label}`}><header><h3>{platform.label}</h3><small>{platform.total} captured responses</small></header><ol>{#each platform.domains.filter(d=>d.domain.includes(query.trim().toLowerCase())).slice(0,limit||undefined) as d}<li><div class="rank-title"><span class="rank-number">{d.rank}</span><button class="domain-link" onclick={()=>{selected=d.domain;tab='details';notice=''}}>{d.domain}</button><strong>{d.percent.toFixed(1)}%</strong></div><div class="bar" aria-hidden="true"><div style:width={`${d.percent}%`}></div></div><small>{d.count} {d.count===1?'response':'responses'} citing this domain</small><select aria-label={`Category for ${d.domain} in ${platform.label}`} value={domains[d.domain]?.category??''} disabled={busy||!loaded} onchange={e=>classify(d.domain,e.currentTarget.value)}><option value="">Unclassified</option>{#each categories as name}<option>{name}</option>{/each}</select></li>{:else}<li class="empty">{platform.total?'No matching domains.':'No captured responses for this selection.'}</li>{/each}</ol></section>{/each}</div>
{:else}
 <label class="domain-select">Domain<select bind:value={selected}><option value="">{inventory.domains[0]?.domain}</option>{#each inventory.domains as d}<option value={d.domain}>{d.domain}</option>{/each}</select></label>
 <h3>{domain}</h3><label class="domain-select">Domain category<select value={domains[domain]?.category??''} disabled={busy||!loaded} onchange={e=>classify(domain,e.currentTarget.value)}><option value="">Unclassified</option>{#each categories as name}<option>{name}</option>{/each}</select></label>
 <p role="status">{notice}</p><p class="definition">Relationships may overlap. Record the relevant crawler and date in notes when checking robots.txt.</p>
 {#if loaded}<div class="table-wrap"><table><thead><tr><th>Platform</th><th>Relationship</th><th>Robots.txt</th><th>Evidence / notes</th></tr></thead><tbody>{#each DOMAIN_PLATFORMS as platform (`${domain}:${platform.id}`)}<DomainPlatformRow {domain} {platform} saved={metadata[`${domain}:${platform.id}`]??null} onSaved={platformSaved}/>{/each}</tbody></table></div>{:else}<p>Loading saved classifications…</p>{/if}
{/if}{/if}
<style>
 .ranking-filters{display:flex;gap:16px;flex-wrap:wrap;margin-top:18px}.ranking-filters label{min-width:160px}.rankings{display:grid;grid-template-columns:repeat(4,minmax(250px,1fr));gap:16px;overflow-x:auto;align-items:start;padding-bottom:12px}.ranking{border:1px solid var(--line);border-radius:8px;background:var(--card)}.ranking header{padding:16px;border-bottom:1px solid var(--line)}.ranking header h3{margin:0}.ranking ol{list-style:none;padding:0;margin:0}.ranking li{padding:14px;border-bottom:1px solid var(--line)}.ranking li:last-child{border-bottom:0}.rank-title{display:flex;align-items:baseline;gap:8px;font-size:12px}.rank-number{color:var(--muted);font-size:11px;min-width:14px}.rank-title .domain-link{flex:1}.rank-title strong{font-size:12px;white-space:nowrap;font-variant-numeric:tabular-nums}.bar{height:4px;background:var(--line);border-radius:3px;margin-top:10px;overflow:hidden}.bar div{height:100%;background:#739c89}.ranking li select{font-size:11px;padding:5px;margin-top:10px}.empty{font-size:12px;color:var(--muted)}
 nav{display:flex;gap:24px;flex-wrap:wrap;border-bottom:1px solid var(--line);margin-bottom:20px}nav button{padding:12px 0;font:inherit;font-size:13px;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted);cursor:pointer}nav button.active{border-bottom-color:#326953;color:var(--text)}.toolbar{display:flex;gap:24px;flex-wrap:wrap;align-items:end}.toolbar>label,form{flex:1;min-width:220px}form{display:flex;align-items:end;gap:12px}form label{flex:1}label{font-size:12px;color:var(--muted)}input,select{font:inherit;padding:8px;margin-top:6px;display:block;width:100%;box-sizing:border-box;border:1px solid var(--line);border-radius:5px;background:var(--card);color:var(--text)}form button{white-space:nowrap;padding:8px;font:inherit;font-size:12px;border:1px solid var(--line);border-radius:5px;background:var(--card);cursor:pointer}p{font-size:12px;line-height:1.6;color:var(--muted)}.table-wrap{overflow:auto}table{border-collapse:separate;border-spacing:0;width:100%;font-size:12px}th{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-weight:500;color:var(--muted)}small{display:block;font-size:10px;font-weight:400;color:var(--muted);margin-top:5px}.domain-link{font:inherit;color:#326953;background:none;border:0;text-align:left;padding:0;cursor:pointer;overflow-wrap:anywhere}.domain-select{display:block;max-width:400px;margin-bottom:20px}h3{font-size:16px}.error{color:var(--danger)}
</style>
